# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a83ee154619c47e5bba50dea12368b7f8e3710a602988d2eb724c42231fb49f5777511da7cd53e9d78006a673070d097c78990c91b8545cc257337b8653513a

test:
  secret_key_base: 53859f80a0e2cfa32ffaca32a0fb6cfb0f26bd653c030057ecd88089603115e796e9b41c329575816f63d53813db690df586e49e9f8d9e409f309b7173d3491b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
